name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push - D9
        id: docker_build_9
        uses: docker/build-push-action@v2
        with:
          context: ./9/
          push: true
          tags: | 
            insready/drupal-commerce:9
            insready/drupal-commerce:latest
      -
        name: Build and push - dev
        id: docker_build_dev
        uses: docker/build-push-action@v2
        continue-on-error: true
        with:
          context: ./dev/
          push: true
          tags: | 
            insready/drupal-commerce:dev
      -
        name: Update repo description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: insready/drupal-commerce