name: ci

on:
  push:
    branches:
      - 'master'
  schedule:
    - cron: '0 0 1 * *'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v3 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push - D10
        id: docker_build_10
        uses: docker/build-push-action@v4
        continue-on-error: true
        with:
          context: ./10/
          push: true
          tags: | 
            insready/drupal-commerce:10
            insready/drupal-commerce:latest
      -
        name: Build and push - D9 dev
        id: docker_build_9_dev
        uses: docker/build-push-action@v4
        continue-on-error: true
        with:
          context: ./9-dev/
          push: true
          tags: | 
            insready/drupal-commerce:9-dev
      -
        name: Build and push - D10 dev
        id: docker_build_10_dev
        uses: docker/build-push-action@v4
        continue-on-error: true
        with:
          context: ./10-dev/
          push: true
          tags: | 
            insready/drupal-commerce:10-dev
            insready/drupal-commerce:dev
      -
        name: Build and push - D11 dev
        id: docker_build_11_dev
        uses: docker/build-push-action@v4
        continue-on-error: true
        with:
          context: ./11-dev/
          push: true
          tags: | 
            insready/drupal-commerce:11-dev
      -
        name: Update repo description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: insready/drupal-commerce